name = "aiken-extra/test_kit"
version = "lithium-Î²"
compiler = "1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "An Aiken utility library containing various tools, mainly for testing purposes"

[repository]
user = "aiken-extra"
project = "test_kit"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2.2.0"
source = "github"

[config.default]
now = 1769000103000
